name: Dev & PR

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'refactor/**'
      - 'feat/**'
      - 'fix/**'
  pull_request:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/init
      - run: pnpm build
      - run: pnpm commitlint --last --verbose
        if: github.event_name == 'push'
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
