name: Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/init
      - run: pnpm build
      - run: pnpm docs:build
      - uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: 'dist'
      - uses: actions/deploy-pages@v2
